# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gisapp', '0005_linestring_point_polygon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linestring',
            old_name='owner_id',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='point',
            old_name='owner_id',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='polygon',
            old_name='owner_id',
            new_name='user_id',
        ),
    ]
