# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 16:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gisapp', '0006_auto_20161125_1400'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LineString',
            new_name='linestring_layer',
        ),
        migrations.RenameModel(
            old_name='Point',
            new_name='point_layer',
        ),
        migrations.RenameModel(
            old_name='Polygon',
            new_name='polygon_layer',
        ),
    ]
