# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 14:11
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisapp', '0007_auto_20161125_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_layers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('user_id', models.IntegerField()),
                ('geom_type', models.CharField(max_length=50)),
            ],
        ),
    ]
