# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 08:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gisapp', '0008_user_layers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='linestring_layer',
        ),
        migrations.DeleteModel(
            name='point_layer',
        ),
        migrations.DeleteModel(
            name='polygon_layer',
        ),
    ]
