# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisapp', '0009_auto_20161130_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_layers',
            name='filename',
            field=models.CharField(default='', max_length=50),
        ),
    ]
