# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 16:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gisapp', '0010_user_layers_filename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_layers',
            old_name='geom_type',
            new_name='color',
        ),
    ]
