# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisapp', '0011_auto_20161204_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_layers',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user_layers',
            name='filename',
            field=models.CharField(max_length=50),
        ),
    ]
