# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 11:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gisapp', '0012_auto_20161204_1716'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_layers',
            new_name='adrian',
        ),
    ]
